version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    ports:
      - 9080:8080
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]

  app:
    build:
      context: ./backend/app/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/realtor-bg
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_SQL_INIT_MODE=never
      - SPRING_DATASOURCE_INITIALIZATION_MODE=never
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=realtor-bg-client
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE=authorization_code
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=sfOJIkBVaMPWD6sgL71aK8MlmxHVkUEZ
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE=openid
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/RealtorBGRealm
      - SPRING_SECURUTY_OAUTH2_RESOURCESERVER_JWT_URI=http://keycloak:8080/realms/RealtorBGRealm/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: realtor-bg
    ports:
      - "3300:3306"
    volumes:
      - "./backend/app/app/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql"
      - "./backend/app/app/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql"

volumes:
  db_data:
